<?php
/**
 * @file
 * The bnm_rates module displays exchange rates information from bnm.org.
 *
 * This module provides a block that lists all of the
 * exchange rates for today.
 */

/**
 * Implements hook_help().
 *
 * @param string $path
 *   Url path.
 * @param mixed $arg
 *   Args passed to function.
 *   See on drupal.org for this hook.
 *
 * @return null|string
 *   Return a result from function.
 */
function bnm_rates_help($path, $arg) {
  if ($path == 'admin/help#bnm_rates') {
    return t('Module bnm_rates pulls xml from bnm.org and displays exchange rates');
  }
}

/**
 * Implements hook_block_info().
 *
 * @return array $block
 *   Contains array with info to display on blocks list in admin backend.
 */
function bnm_rates_block_info() {
  $blocks['block_bnm_rates'] = array(
    'info' => t('BNM currency rates'),
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 *
 * @param string $delta
 *   The block id.
 *
 * @return array $block
 *   This array contains info about blocks for this module.
 */
function bnm_rates_block_view($delta = '') {
  global $language;
  // This example is adapted from node.module.
  $block = array();

  $date = date("d.m.Y");
  $lang = $language->language;
  switch ($delta) {
    case 'block_bnm_rates':
      $block['subject'] = t('BNM currency rates @date', array('@date' => $date));
      module_load_include('php', 'bnm_rates', 'include/bnm_rates_functions.inc');
      if ($rates = bnm_rates_get($date, $lang, 1)) {
        $block['content'] = array(
          '#theme' => 'bnm_rates_block_rates',
          '#title' => t('BNM currency rates'),
          '#rates' => $rates,
        );
      }
      else {
        $block['content'] = t('No content available.');
      }
      break;
  }
  return $block;
}


/**
 * Implements hook_theme().
 */
function bnm_rates_theme($existing, $type, $theme, $path) {
  $bnm_rates_themes = array(
    'bnm_rates_block_rates' => array(
      'variables' => array('rates' => NULL, 'limit' => 10),
      'template' => 'templates/bnm_rates_block_rates',
    ),
  );

  return $bnm_rates_themes;
}
